### ISSUE TITLE
Spring Cloud Gateway's `DedupeResponseHeader` not working as expected

### ISSUE THREAD

**Issue by ferrarijh** [ferrarijh/webflux-react-websocket-chat#32]
Response header shows `access-control-allowed-origins: *` while the value should be `http://some.origin:3000` under below settings.

`application.yml`: 
```
spring:
  cloud:
    gateway: 
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://some.origin:3000"
      routes:
        - id: hello
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers RETAIN_LAST
```
